# Generated by Django 5.1.4 on 2024-12-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='QTY_Eldoret',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='QTY_Kisumu',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='QTY_Mombasa',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='QTY_Nairobi_A',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='QTY_Nairobi_B',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='QTY_Nakuru',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='QTY_Nyeri',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='TOTAL_QTY',
        ),
    ]
