# Generated by Django 5.1.4 on 2024-12-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_salesdata_qty_eldoret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='QTY_Eldoret',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='QTY_Kisumu',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='QTY_Mombasa',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='QTY_Nairobi_A',
            field=models.FloatField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='QTY_Nairobi_B',
            field=models.FloatField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='QTY_Nakuru',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='QTY_Nyeri',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='TOTAL_QTY',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
