# Generated by Django 5.1.4 on 2024-12-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_salesdata_qty_eldoret_salesdata_qty_kisumu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='QTY_Eldoret',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='QTY_Kisumu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='QTY_Mombasa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='QTY_Nairobi_B',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='QTY_Nakuru',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='QTY_Nyeri',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='TOTAL_QTY',
            field=models.FloatField(default=0),
        ),
    ]
