# Generated by Django 5.1.4 on 2024-12-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_salesdata_qty_eldoret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('sub_division', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('target_value', models.FloatField()),
            ],
        ),
    ]
