# Generated by Django 5.1.4 on 2024-12-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_targetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('subdivision', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('sales_target', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='TargetData',
        ),
    ]
