# Generated by Django 5.1.4 on 2024-12-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_salestarget_delete_targetdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salestarget',
            old_name='month',
            new_name='Month',
        ),
        migrations.RenameField(
            model_name='salestarget',
            old_name='region',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='salestarget',
            old_name='sales_target',
            new_name='Sales',
        ),
        migrations.RenameField(
            model_name='salestarget',
            old_name='subdivision',
            new_name='Sub_division',
        ),
    ]
