# Generated by Django 5.1.4 on 2024-12-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_rename_month_salestarget_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestarget',
            name='Year',
            field=models.IntegerField(default=2024),
        ),
    ]
